Update the cargo installation instructions to include --locked
The ignore-0.4.19 package has a breaking change for the current build
configuration as it requires Rust 1.63 or greater. The cargo install
command ignores the lock file producing the following error:
error[E0658]: use of unstable library feature 'scoped_threads'
    --> /build/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.19/src/walk.rs:1285:9
The locked flag keeps the package pinned at 0.4.18.

See:
Cargo install lock issue: https://github.com/rust-lang/cargo/issues/7169
ignore commit: https://github.com/BurntSushi/ripgrep/commit/e95254a86f484eec663be4714924d91d3cf39cb8