Fix panic due to partial jumplist sync in jump_view_*
Test Document
-------------
```
test
```

Steps to Reproduce
------------------
1. %        # select_all
1. Ctrl-w s # hsplit
1. gf       # goto_file
1. Ctrl-w w # rotate_view
1. d        # delete_selection
1. Ctrl-w w # rotate_view
1. Ctrl-o   # jump_backward

Debug
-----
`thread 'main' panicked at 'assertion failed:
char_idx <= slice.len_chars()', helix-core/src/graphemes.rs:168:5`

Release
-------
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Char index out of bounds: char index 4, Rope/RopeSlice char length 0',
ropey-1.6.1/src/slice.rs:360:41`

Description
-----------
The jumplist selections are not completely synced when moving between
views. Currently, only the active document in every view is checked. The
fix syncs all documents in the destination view's jumplist only.